server:
  port: 8081

spring:
  application:
    name: sensor-ingestion-service
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # ESTA LINHA ABAIXO É A MAIS IMPORTANTE:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    properties:
      spring.json.add.type.headers: false

topics:
  sensor-leitura: producao.sensor.leitura
  maquina-parada: producao.maquina.parada